#!/bin/bash

set -euo pipefail

BASE_DIR="$(dirname $(realpath "${0}"))"


function usage {
    echo "\
Usage: run [OPTION...] COMMAND
Execute commands for deploying the homelab.

Commands:
    terraform    Run terraform to create the containers.
    ansible      Run ansible on the containers created by terraform.
    destroy      Destroy the whole infrastructure.
    full         Run terraform followed by ansible.

Optional arguments:
    -y/--yes     Do not ask for interactive confirmation.
    -h/--help    Print this help message and exit."
}


function run-at (
    cd "${1}"
    $"${@:2}"
)


function error {
    echo "${@}" 1>&2
}


function die {
    error "${@}" | return 1
}


function run-terraform {
    local quiet_flag="${1}"
    local command="${2}"
    local var_file="${BASE_DIR}/private/server.tfvars"

    run-at terraform/server \
        terraform "${command}" ${quiet_flag} -var-file "${var_file}" "${@:3}"
}


function run-ansible {
    local tf_generated="${BASE_DIR}/tf-generated"
    local playbook="${BASE_DIR}/ansible/deploy-homelab.yml"

    [[ -d "${tf_generated}" ]] ||
        die "No 'tf-generated' directory found. Run terraform first."

    ansible-playbook -i "${tf_generated}/ansible-services-inventory.ini" "${playbook}" "${@}"
}


function terraform-apply {
    local quiet_flag="${1}"

    run-terraform "${quiet_flag}" apply
}


function terraform-destroy {
    local quiet_flag="${1}"

    run-terraform "${quiet_flag}" destroy
}


function run-command {
    local quiet_flag="${1}"
    local command="${2}"

    case "${command}" in
        terraform)
            terraform-apply "${quiet_flag}" ;;
        ansible)
            run-ansible "${@:3}" ;;
        destroy)
            terraform-destroy "${quiet_flag}" ;;
        full)
            terraform-apply "${quiet_flag}" &&
            run-ansible
            ;;
        *)
            die "No command '${command}'."
            ;;
    esac
}

function main {
    source "${BASE_DIR}/private/environment"

    local options
    options=$(getopt -o hy -l help,yes -- "${@}")
    eval set -- "$options"

    local quiet_flag=""

    while true; do
        case "${1}" in
            -h|--help)
                usage && return 0
                ;;
            -y|--yes)
                quiet_flag="-auto-approve"
                ;;
            --) shift ;&
            *) break ;;
        esac
        shift
    done

    local command="${1}"
    shift

    run-command "${quiet_flag}" "${command}" "${@}"
}


main "${@}"
