version: "3"

services:
  proxy:
    image: "{{ nginx_image }}"
    restart: "always"

    volumes:
      - "{{ service_data_dir }}/etc/nginx:/etc/nginx"
      - "{{ common_certs_dir }}:/certs:ro"

    ports:
      - "80:80"
      - "443:443"

  navidrome_:
    image: "{{ navidrome_image }}"
    restart: "always"
    user: "{{ service_uid }}:{{ service_uid }}"

    environment:
      ND_SCANSCHEDULE: "1h"

    volumes:
      - "{{ service_data_dir }}/navidrome_data:/data"
      - "{{ container_data_dir }}/shared/music:/music:ro"
