version: "3"

services:
  proxy:
    image: "nginx:mainline-alpine-slim"
    restart: "always"

    volumes:
      - "{{ service_data_dir }}/etc/nginx:/etc/nginx"
      - "{{ common_certs_dir }}:/certs:ro"

    ports:
      - "80:80"
      - "443:443"

  navidrome_:
    image: "deluan/navidrome:latest"
    restart: "always"

    environment:
      ND_SCANSCHEDULE: "1h"

    volumes:
      - "{{ service_data_dir }}/navidrome_data:/data"
      - "{{ container_data_dir }}/shared/music:/music"
