version: "3"

services:
  pihole:
    container_name: "pihole"
    image: "{{ pihole_image }}"
    network_mode: "host"

    environment:
      TZ: "America/Sao_Paulo"
      WEBPASSWORD_FILE: "/run/secrets/webpassword"

    volumes:
      - "{{ dnsmasq_config_dir }}:/etc/dnsmasq.d"
      - "{{ pihole_config_dir }}:/etc/pihole"

    cap_add:
      - "NET_ADMIN"

    restart: "unless-stopped"

    secrets:
      - "webpassword"

secrets:
  webpassword:
    file: "./webpassword"
