- name: "Import custom vars"
  ansible.builtin.include_vars: "vars.yml"

- name: "Ensure conf dir exists"
  file:
    path: "{{ item }}"
    state: "directory"
  loop:
    - "{{ pihole_data_dir }}"
    - "{{ pihole_data_dir }}/etc"
    - "{{ dnsmasq_config_dir }}"
    - "{{ pihole_config_dir }}"
    - "{{ pihole_custom_hosts_dir }}"

- name: "Copy webpassword"
  ansible.builtin.copy:
    src: "{{ webpassword_file }}"
    dest: "{{ webpassword_remote_file }}"
  register: "webpassword"

- name: "Copy dhcp assignments"
  ansible.builtin.copy:
    src: "{{ dhcp_assignments_file }}"
    dest: "{{ dnsmasq_config_dir }}/04-pihole-static-dhcp.conf"
  register: "dhcp_assignments"

- name: "Ensure setupVars.conf is properly included"
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', '{{ setupVars_file }}') }}"
    path: "{{ pihole_config_dir }}/setupVars.conf"
    create: true
  register: "setupVars"

- name: "Copy service hosts"
  ansible.builtin.copy:
    src: "{{ service_hosts_file }}"
    dest: "{{ pihole_custom_hosts_dir }}/01-service-hosts"

- name: "Copy static hosts"
  ansible.builtin.copy:
    src: "{{ static_hosts_file }}"
    dest: "{{ pihole_custom_hosts_dir }}/02-static-hosts"

- name: "Merge files into a single custom.list"
  ansible.builtin.assemble:
    src: "{{ pihole_custom_hosts_dir }}"
    dest: "{{ pihole_config_dir }}/custom.list"
  register: "custom_list"

- name: "Set service to be redeployed"
  ansible.builtin.set_fact:
    restart_docker: true
  when: "webpassword.changed or  dhcp_assignments.changed or setupVars.changed or custom_list.changed"
