version: "3"

services:
  letsencrypt:
    container_name: "letsencrypt"
    image: "{{ certbot_dns_multi_image }}"

    volumes:
      - "${PWD}/update_certificate.sh:/root/update_certificate.sh"
      - "{{ letsencrypt_config_dir }}:/etc/letsencrypt"
      - "{{ common_certs_dir }}:/certs"

    entrypoint: ["/bin/bash", "-c"]
    command: "/root/update_certificate.sh"

    restart: "unless-stopped"
