- name: "Import custom vars"
  ansible.builtin.include_vars: "vars.yml"

- name: "Ensure directories exist"
  file:
    path: "{{ item }}"
    state: "directory"
  loop:
    - "{{ common_certs_dir }}"
    - "{{ letsencrypt_cli_ini_dir }}"

- name: "Copy base cli.ini"
  ansible.builtin.copy:
    src: "01-certbot-base-configs.ini"
    dest: "{{ letsencrypt_cli_ini_dir }}/"

- name: "Copy private cli.ini"
  ansible.builtin.copy:
    src: "{{ letsencrypt_private_dir }}"
    dest: "{{ letsencrypt_cli_ini_dir}}/02-private.ini"

- name: "Merge files into a single custom.list"
  ansible.builtin.assemble:
    src: "{{ letsencrypt_cli_ini_dir }}"
    dest: "{{ letsencrypt_config_dir }}/cli.ini"
  register: "cli_ini"

- name: "Copy dns-multi.ini"
  ansible.builtin.copy:
    src: "{{ dns_multi_ini_file }}"
    dest: "{{ letsencrypt_config_dir }}"
  register: "dns_multi_ini"

- name: "Configure update_certificate.sh"
  ansible.builtin.template:
    src: "{{ update_certificate_file }}"
    dest: "{{ compose_dir }}"
    mode: 0744
  register: "update_certificate_sh"

- name: "Set service to be redeployed"
  ansible.builtin.set_fact:
    restart_docker: true
  when: "cli_ini.changed or dns_multi_ini.changed or update_certificate_sh.changed"
