subservices:
  - name: "sonarr"
    image: "{{ sonarr_image }}"
    port: 8989
    volumes:
      - "{{ service_data_dir }}/sonarr:/config"
      - "{{ container_data_dir }}/shared/series:/series"
      - "{{ container_data_dir }}/shared/unsorted/series:/unsorted"
      - "{{ container_data_dir }}/shared/downloads:/downloads"
  - name: "radarr"
    image: "{{ radarr_image }}"
    port: 7878
    volumes:
      - "{{ service_data_dir }}/radarr:/config"
      - "{{ container_data_dir }}/shared/movies:/movies"
      - "{{ container_data_dir }}/shared/unsorted/movies:/unsorted"
      - "{{ container_data_dir }}/shared/downloads:/downloads"
  - name: "lidarr"
    image: "{{ lidarr_image }}"
    port: 8686
    volumes:
      - "{{ service_data_dir }}/lidarr:/config"
      - "{{ container_data_dir }}/shared/music:/music"
      - "{{ container_data_dir }}/shared/downloads:/downloads"
  - name: "bazarr"
    image: "{{ bazarr_image }}"
    port: 6767
    volumes:
      - "{{ service_data_dir }}/bazarr:/config"
      - "{{ container_data_dir }}/shared/series:/series"
      - "{{ container_data_dir }}/shared/movies:/movies"
  - name: "prowlarr"
    image: "{{ prowlarr_image }}"
    port: 9696
    volumes:
      - "{{ service_data_dir }}/prowlarr:/config"
