- name: "Configure pihole lxc.cap.drop"
  hosts: "proxmox"
  remote_user: "root"

  vars:
    lxc_config_path: "/etc/pve/lxc/10053.conf"

  tasks:
    - name: "Check if lcx.cap.drop configuration is already in file"
      ansible.builtin.command: "grep '^lxc\\.cap\\.drop:\\s*$' {{ lxc_config_path }}"
      register: "lxc_cap_drop"
      failed_when: "lxc_cap_drop.rc >= 2"
      changed_when: false

    - name: "Edit pihole lxc configuration"
      lineinfile:
        path: "{{ lxc_config_path }}"
        line: "lxc.cap.drop:"
      register: "pihole_lxc_config"
      when: "lxc_cap_drop.rc != 0"

    - name: "Restart pihole lxc container"
      ansible.builtin.raw: "pct reboot 10053"
      when: "pihole_lxc_config.changed"
