- name: "Ensure container dir exists"
  ansible.builtin.file:
    path: "/container"
    state: "directory"

- name: "Copy compose file"
  ansible.builtin.copy:
    src: "services/{{ ansible_hostname }}/docker-compose.yml"
    dest: "/container/docker-compose.yml"

- name: "Check if custom tasks exist"
  delegate_to: "localhost"
  ansible.builtin.stat:
    path: "services/{{ ansible_hostname }}/tasks.yml"
  register: "custom_tasks"

- name: "Include custom tasks"
  ansible.builtin.include_tasks:
    file: "services/{{ ansible_hostname }}/tasks.yml"
  when: "custom_tasks.stat.exists"

- name: "Bring service up"
  block:
    - name: "Take service down if configuration changed"
      community.docker.docker_compose:
        project_src: "/container"
        state: "absent"
      when: "restart_docker | default(false)"

    - name: "Start service"
      community.docker.docker_compose:
        project_src: "/container"
        build: true
        pull: true
        remove_orphans: true
        state: "present"
  environment:
    PWD: "{{ compose_dir }}"
    SERVICE_DIR: "{{ services_data_dir }}/{{ ansible_hostname }}"

- name: "Prune Docker data"
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true
