- name: "Deploy service with Docker"
  hosts: "service_containers"
  remote_user: "root"

  tasks:
    - name: "Check if deployment files are the same"
      ansible.builtin.copy:
        src: "services/{{ ansible_hostname }}/"
        dest: "/container"
      check_mode: "yes"
      register: "deployment_files_would_have"

    - name: "Check if secret files are the same"
      ansible.builtin.copy:
        src: "../private/{{ ansible_hostname }}/"
        dest: "/private"
      check_mode: "yes"
      register: "private_files_would_have"

    - name: "Redeploy service."
      include_tasks: "redeploy-service.yml"
      when: "deployment_files_would_have.changed or private_files_would_have.changed"
