- name: Install Docker
  hosts: service_containers
  remote_user: root

  tasks:
  - name: Update Alpine image
    community.general.apk:
      upgrade: true
      update_cache: true

  - name: Install Docker and Docker Compose
    community.general.apk:
      name: docker,docker-cli-compose
