- name: "Install Docker"
  hosts: "service_containers"
  remote_user: "root"

  tasks:
  - name: "Update Alpine image"
    community.general.apk:
      upgrade: true
      update_cache: true

  - name: "Install Docker and Docker Compose"
    community.general.apk:
      name: "docker"

  - name: "Enable and start Docker service"
    ansible.builtin.service:
      name: "docker"
      enabled: true
      state: "started"

  - name: "Install Docker Python module"
    pip:
      name:
        - "docker<7.0.0"
        - "docker-compose"
      extra_args: "--no-build-isolation"
