- name: "Check if docker-compose.yml is in place"
  stat:
    path: "/container/docker-compose.yml"
  register: "docker_compose_yml"

- name: "Ensure the service is down"
  community.docker.docker_compose:
    project_src: "/container"
    state: "absent"
    remove_orphans: true
  when: "docker_compose_yml.stat.exists"

- name: "Prune Docker data"
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true

- name: "Copy deployment files"
  ansible.builtin.copy:
    src: "services/{{ ansible_hostname }}/"
    dest: "/container"
  when: "deployment_files_would_have.changed"

- name: "Copy private files"
  ansible.builtin.copy:
    src: "../private/{{ ansible_hostname }}/"
    dest: "/private"
  when: "private_files_would_have.changed"

- name: "Start service"
  community.docker.docker_compose:
    project_src: "/container"
    build: true
    pull: true
    stopped: false
    state: "present"
