- name: "Configure pihole lxc.cap.drop"
  ansible.builtin.import_playbook: "configure-pihole-cap.yml"

- name: "Install Python"
  ansible.builtin.import_playbook: "install-python.yml"

- name: "Install Docker"
  ansible.builtin.import_playbook: "install-docker.yml"

- name: "Deploy services"
  ansible.builtin.import_playbook: "deploy-services.yml"

- name: "Configure Pihole"
  ansible.builtin.import_playbook: "configure-pihole.yml"
