version: "3"

services:
  nfs_server:
    image: "{{ nfs_server_image }}"
    restart: "always"

    volumes:
      - "{{ service_data_dir }}/etc/exports:/etc/exports"
      - "{{ container_data_dir }}/shared:/nfs/shared"

    ports:
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "111:111/tcp"
      - "111:111/udp"

    cap_add:
      - "SYS_ADMIN"
